USE OdessaMasonFireworks;
--DROPPING TABLES IN ORDER
DROP TABLE IF EXISTS SaleProducts;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS OrderProducts;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Brands;
DROP TABLE IF EXISTS ProductTypes;

--CREATING TABLES
DROP TABLE IF EXISTS Members;
CREATE TABLE Members
(
	[MemberID] INT IDENTITY PRIMARY KEY NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Position] NVARCHAR(100),
	[JoinDate] DATE,
	[Address] NVARCHAR(100),
	[City] NVARCHAR(100),
	[State] CHAR(2),
	[PostalCode] NVARCHAR(10),
	[Email] NVARCHAR(100),
	[Phone] NVARCHAR(20)
);

DROP TABLE IF EXISTS Customers;
CREATE TABLE Customers 
(
	[CustomerID] INT IDENTITY PRIMARY KEY NOT NULL,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(100),
	[City] NVARCHAR(100),
	[State] CHAR(2),
	[PostalCode] NVARCHAR(10),
	[Email] NVARCHAR(100),
	[Phone] NVARCHAR(20)
);

DROP TABLE IF EXISTS ProductTypes;
CREATE TABLE ProductTypes
(
	[TypeID] INT IDENTITY PRIMARY KEY NOT NULL,
	[TypeName] NVARCHAR(50) NOT NULL,
	[TypeDesc] NVARCHAR(MAX)
);

DROP TABLE IF EXISTS Brands;
CREATE TABLE Brands
(
	[BrandID] INT IDENTITY PRIMARY KEY NOT NULL,
	[BrandName] NVARCHAR(50) NOT NULL,
);

DROP TABLE IF EXISTS Products;
CREATE TABLE Products
(
	[ProductID] INT IDENTITY PRIMARY KEY NOT NULL,
	[ProductName] NVARCHAR(150) NOT NULL,
	[Description] NVARCHAR(MAX),
	[TypeID] INT FOREIGN KEY REFERENCES ProductTypes(TypeID),
	[BrandID] INT FOREIGN KEY REFERENCES Brands(BrandID),
	[UnitsInStock] SMALLINT,
	[UnitsOrdered] SMALLINT,
	[UnitType] NVARCHAR(20),
	[UnitsPerBox] SMALLINT,
	[BoxesPerCase] SMALLINT,
	[CostPerUnit] MONEY,  
	[PricePerUnit] MONEY,
	[ProductImage] NVARCHAR(100)
);

DROP TABLE IF EXISTS Orders;
CREATE TABLE Orders
(
	[OrderID] INT IDENTITY PRIMARY KEY NOT NULL,
	[PONumber] VARCHAR(50),
	[OrderDate] DATE,
	[OrderTotal] MONEY
);

DROP TABLE IF EXISTS OrderProducts;
CREATE TABLE OrderProducts 
(
	[OrderProductID] INT IDENTITY PRIMARY KEY NOT NULL,
	[OrderID] INT FOREIGN KEY REFERENCES Orders(OrderID) NOT NULL,
	[ProductID] INT FOREIGN KEY REFERENCES Products(ProductID) NOT NULL,
	[OrderQuantity] SMALLINT NOT NULL
);

DROP TABLE IF EXISTS Sales;
CREATE TABLE Sales
(
	[SaleID] INT IDENTITY PRIMARY KEY NOT NULL,
	[SaleDate] DATE NOT NULL,
	[CustomerID] INT FOREIGN KEY REFERENCES Customers(CustomerID) NOT NULL,
	[SaleTotal] MONEY
)

DROP TABLE IF EXISTS SaleProducts;
CREATE TABLE SaleProducts
(
	[SaleProductID] INT IDENTITY PRIMARY KEY NOT NULL,
	[SaleID] INT FOREIGN KEY REFERENCES Sales(SaleID) NOT NULL,
	[ProductID] INT FOREIGN KEY REFERENCES Products(ProductID) NOT NULL,
	[SaleQuantity] SMALLINT 
);